# Permalinks
permalink:           pretty

# Setup
title:               J.C. Nachman
tagline:             My Data Science Blog
url:                 http://jcnachman.github.io
paginate:            2
baseurl:             ""

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed

# About/contact
author:
  name:              Joanna Nachman
  url:               https://www.linkedin.com/in/joanna-nachman-msis-b7847b15/
  email:             jcnachman@gmail.com

# Custom vars
version:             2.0.0
github:
  repo:              https://github.com/jcnachman

# Gems
gems:
  - jekyll-paginate
  - jekyll-gist

# Page List
pages_list:       
  About: '/about'
  Archive: '/archive'
  Feed: '/index.html'

